name: extract-cache
on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: restore v3-part1
        uses: actions/cache/restore@v4
        with:
          path: p1
          key: stryker-v3-part1-x
          restore-keys: stryker-v3-part1-
      - name: restore v3-part2
        uses: actions/cache/restore@v4
        with:
          path: p2
          key: stryker-v3-part2-x
          restore-keys: stryker-v3-part2-
      - name: restore v3-part3
        uses: actions/cache/restore@v4
        with:
          path: p3
          key: stryker-v3-part3-x
          restore-keys: stryker-v3-part3-
      - name: restore v3-part4
        uses: actions/cache/restore@v4
        with:
          path: p4
          key: stryker-v3-part4-x
          restore-keys: stryker-v3-part4-
      - name: 解析存活变异体
        run: node .github/extract-survivors.js
